#apiVersion: v1
#kind: Secret
#metadata:
#  name: devicetwin-certs
#data:
#  # base64 encoded X509 certificate files
#  ca.crt: LS0tLS1CRUdJTi...WEZuaFUzCmJ3bmZwYzRKNWNHdzg3c3AxSzY3R2Q3VHpFTUJPdXp5alE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#  server.crt: LS0tLS1CRUdJTi...bUhVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#  server.key: LS0tLS1CRUdJTi...FLM3hNbklkWTRuaUtzbFoKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: devicetwin-pv-volume-twin
  labels:
    type: local
    app: devicetwin
spec:
  storageClassName: manual
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devicetwin-pv-claim-twin
  labels:
    app: devicetwin
spec:
  #storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicetwin
spec:
  selector:
    matchLabels:
      app: devicetwin
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: devicetwin
        tier: frontend
        track: stable
    spec:
      containers:
        - name: devicetwin
          image: sonicblue/iot-devicetwin
          volumeMounts:
            - name: certs
              mountPath: /srv/certs
            - name: config
              mountPath: /srv/config
          env:
            - name: PORT
              value: "8040"
            - name: DRIVER
              value: "postgres"
            - name: DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-twin
                  key: DATASOURCE
            - name: MQTTURL
              value: "mosquitto"
            - name: MQTTPORT
              value: "8883"
            - name: CERTSDIR
              value: "/srv/certs"
            - name: CONFIGDIR
              value: "/srv/config"
          ports:
            - containerPort: 8040
      volumes:
        - name: certs
          secret:
            secretName: devicetwin-certs
        - name: config
          persistentVolumeClaim:
            claimName: devicetwin-pv-claim-twin
---
apiVersion: v1
kind: Service
metadata:
  name: devicetwin
spec:
  selector:
    app: devicetwin
    tier: frontend
  ports:
    - port: 8040
      protocol: TCP
