apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicetwin
spec:
  selector:
    matchLabels:
      app: devicetwin
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: devicetwin
        tier: frontend
        track: stable
    spec:
      containers:
        - name: devicetwin
          image: iot-devicetwin
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "8040"
            - name: DRIVER
              value: "postgres"
            - name: DATASOURCE
              value: "dbname=devicetwin host=postgres-twin user=manager password=dZfYe5Z80J3B sslmode=disable"
            - name: MQTTURL
              value: "192.168.64.11"
            - name: MQTTPORT
              value: "8883"
            - name: CONFIGDIR
              value: "/srv/certs"
          ports:
            - containerPort: 8040
---
apiVersion: v1
kind: Service
metadata:
  name: devicetwin
spec:
  selector:
    app: devicetwin
    tier: frontend
  ports:
    - port: 8040
      protocol: TCP
